# This workflow will install Python dependencies, run tests, lint with a single version of Python, and upload a coverage report to Codecov
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push

jobs:
  test:
    name: Run pytest and collect coverage for Codecov
    runs-on: ubuntu-latest, macos-latest, windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e
        pip install pytest pytest-cov
  
    - name: Run tests
      run: |
        pytest -v
    - name: Generate Codecov coverage report
      run: |
        pytest --cov-setupexample --cov_report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        token: 
